name: CI

on:
  push:
    branches:
      - winfredB  # Change this to your branch name if needed
  pull_request:
    branches:
      - main      # Change this to your base branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Change to the desired version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Your test commands here
