name: CI

on:
  push:
    branches:
      - winfredB
      - mukiibi_change
  pull_request:
    branches:
      - main
      - mukiibi_change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Update to your installed version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #- name: Run tests
     # run: |
      #  python -m unittest discover  # Example command for running tests
