name: CI Pipeline

# Trigger this workflow on pushes to the 'winfredB' branch or on pull requests
on:
  push:
    branches:
      - winfredB
  pull_request:
    branches:
      - winfredB

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment for Django
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run database migrations
    - name: Run migrations
      run: python manage.py migrate

    # Run Django tests
    - name: Run Django tests
      run: python manage.py test

    # Set up Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify your Node.js version

    # Install frontend dependencies
    - name: Install frontend dependencies
      run: |
        cd frontend  # Navigate to your frontend directory if applicable
        npm install

    # Run frontend tests (adjust if you have a specific test command)
    - name: Run frontend tests
      run: |
        cd frontend  # Navigate to your frontend directory
        npm test
