name: CI

on:
  push:
    branches:
      - winfredB  # Change to your branch name if different
  pull_request:
    branches:
      - winfredB  # Change to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure you're using a compatible version

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found!"
          exit 1
        fi

    - name: Run Tests
      run: |
        # Add commands to run your tests here
        echo "Add your test commands here."

    - name: Check for any issues
      run: |
        # Optionally, you can add linting or other checks here
        echo "Check for issues here."
